name: mgpg-tools
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3
  - bioconda::odgi=0.8.3
  - bioconda::seqkit=2.5.1
  - conda-forge::prettytable=3.10.0
  - bioconda::gfapy=1.2.3
  - bioconda::clustalw=2.1
  - bioconda::gffread=0.12.7
  - bioconda::aster=1.16
  