name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Cache conda
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 6
      with:
        path: ~/conda_pkgs_dir
        key:
          mgpgtools-${{ runner.os }}-conda-${{ matrix.python-version }}-${{
          env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: bioconda,conda-forge,defaults
        channel-priority: false
        activate-environment: mgpg-tools
        environment-file: environment.yml
    - shell: bash -el {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort
    - shell: bash -el {0}
      run: |
        mamba install pylint flake8 pytest
    - shell: bash -el {0}
      run: |
        pylint -E $(git ls-files '*.py')
    - name: Lint with flake8
      shell: bash -el {0}
      run: |
        cd ${{ github.workspace }}
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
