name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: bioconda,conda-forge,defaults
          channel-priority: true
          activate-environment: mgpg-tools
          environment-file: environment.yml
    - name: Install dependencies
      run: |
        mamba install conda-forge::pylint
    - name: Analysing the code with pylint
      run: |
        pylint -E $(git ls-files '*.py')
