name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Cache conda
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          mgpgtools-${{ runner.os }}-conda-${{ matrix.python-version }}-${{
          env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: bioconda,conda-forge,defaults
        channel-priority: true
        activate-environment: mgpg-tools
        use-only-tar-bz2: true
        environment-file: environment.yml
    - shell: bash -el {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort
    - shell: bash -el {0}
      run: |
        mamba install conda-forge::pylint
    - shell: bash -el {0}
      run: |
        pylint -E $(git ls-files '*.py')
